export enum ActionType {
  SEARCH_PACKAGE = "SEARCH_PACKAGE",
  SEARCH_PACKAGE_SUCCESS = "SEARCH_PACKAGE_SUCCESS",
  SEARCH_PACKAGE_FAILURE = "SEARCH_PACKAGE_FAILURE",
  SEARCH_PACKAGE_DETAILS = "SEARCH_PACKAGE_DETAILS",
  SEARCH_PACKAGE_DETAILS_SUCCESS = "SEARCH_PACKAGE_DETAILS_SUCCESS",
  SEARCH_PACKAGE_DETAILS_FAILURE = "SEARCH_PACKAGE_DETAILS_FAILURE",
  FETCH_PACKAGE = "FETCH_PACKAGE",
  FETCH_PACKAGE_SUCCESS = "FETCH_PACKAGE_SUCCESS",
  FETCH_PACKAGE_FAILURE = "FETCH_PACKAGE_FAILURE",
}
